### ISSUE TITLE
Open Source or Proprietary ?

### ISSUE THREAD

**Issue by sbaconnais** [TomTasche/OpenDocument.droid#68]
Hello,

There is more and more proprietary binaries in this app ... Can it still really be called "Open Source" 

Please sweep away those binaries, for the love of open source.

**Comment by TomTasche** [comment]
We still do love open source and are committed to keep this app open source. The core of this app (parsing and displaying documents) will always be open source. However we're using some third party services in order to make our and our user's lifes easier. Google Analytics simply is state of the art and offers us ways to understand how you're using our app, etc.

If you have any specific suggestions how we could improve this issue please leave a comment. Closing for now...
